// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrKB1iLsoTIgIjvM1Db5My-k_X9DRL8I',
    appId: '1:335001544449:web:10dfd15f943154a2b05d00',
    messagingSenderId: '335001544449',
    projectId: 'buzzats',
    authDomain: 'buzzats.firebaseapp.com',
    storageBucket: 'buzzats.appspot.com',
    measurementId: 'G-B8C70BRYLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZgUewR6EPt_cMJWp4bH5SNP5a6iufQQ',
    appId: '1:335001544449:android:5bab0a15e6b5fb95b05d00',
    messagingSenderId: '335001544449',
    projectId: 'buzzats',
    storageBucket: 'buzzats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjEvwEHisBcWIA50FNcsz7msypW3BeDM',
    appId: '1:335001544449:ios:ea7ee5e304aafdc7b05d00',
    messagingSenderId: '335001544449',
    projectId: 'buzzats',
    storageBucket: 'buzzats.appspot.com',
    iosClientId: '335001544449-0ogs57ltsdqncq35f4qe41ja6re9rkhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjEvwEHisBcWIA50FNcsz7msypW3BeDM',
    appId: '1:335001544449:ios:b6cb67e51d3c6cd0b05d00',
    messagingSenderId: '335001544449',
    projectId: 'buzzats',
    storageBucket: 'buzzats.appspot.com',
    iosClientId: '335001544449-lqltbsmthnu9o9qahh5tuttr4rtncgo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp1.RunnerTests',
  );
}
